import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import AppShell from "@/components/app-shell";
import { Layout, LayoutBody, LayoutHeader } from "@/components/custom/layout";
import { ThemeToggle } from "@/components/theme-switch";
import { UserNav } from "@/components/user-nav";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AppShell>
            <Layout>
              <LayoutHeader>
                <div className="flex w-full items-center justify-end">
                  <div className="flex items-center space-x-4">
                    <ThemeToggle />
                    <UserNav />
                  </div>
                </div>
              </LayoutHeader>
              <LayoutBody>{children}</LayoutBody>
            </Layout>
          </AppShell>
        </ThemeProvider>
      </body>
    </html>
  );
}
